SERVER_NAME = 'localhost:5000'

#Database
DB_USERNAME = ''
DB_PASSWORD = ''
DB_SERVER = ''
DB_NAME = ''

SECRET_KEY = 'SomeString'
SECURITY_REGISTERABLE = True
SECURITY_PASSWORD_SALT = 'SomePasswordSalt'
SECURITY_SEND_REGISTER_EMAIL = False

VAPID_PUBLIC_KEY = ""
VAPID_PRIVATE_KEY = ""
VAPID_CLAIM_EMAIL = ""