"""empty message

Revision ID: 7a6b8fd6914e
Revises: e65eba073e0b
Create Date: 2019-11-17 17:54:23.241482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a6b8fd6914e'
down_revision = 'e65eba073e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('push_subscription', 'subscription_json',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('push_subscription', 'subscription_json',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
